# Setup
title:               Interplanetary Initiative Lab
tagline:             'An Interplanetary Initiative Operation'
description:         "A more frequently updated website for the lab's specifications"
paginate:            5
permalink:           pretty

include:
  - "_images"
  - "_pages"

# Gems
plugins:
  - jekyll-paginate
