title:               Interplanetary Initiative Lab
tagline:             'An Interplanetary Initiative Operation'
description:         "A more frequently updated website for the lab's specifications"
paginate:            5
paginate_path: "/lab-news/page:num/"
permalink:           pretty
domain: interplanetarylab.github.io
url: https://interplanetarylab.github.io
baseurl: / # change to /testing-website/ for git pages

include:
  - "_images"
  - "_pages"
  - "lab-news"

# Build settings
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
