# Setup
title:               Interplanetary Initiative Lab
tagline:             'An Interplanetary Initiative Operation'
description:         "A more frequently updated website for the lab's specifications"
paginate:            5
paginate_path: "/lab-news/page:num/"
permalink:           pretty

include:
  - "_images"
  - "_pages"
  - "lab-news"

# Gems
plugins:
  - jekyll-paginate
