# Setup
title:               Interplanetary Initiative Lab
tagline:             'An Interplanetary Initiative'
description:         'A more frequently updated website for the labs specifications'
baseurl:             ''
paginate:            5
permalink:           pretty


include:
  - "_images"
  - "_pages"

# Gems
plugins:
  - jekyll-paginate
