name: Github Actions
on: [push]
jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: echo "performing readme merge from publications document"
      - uses: actions/checkout@v1
      - name: "performing command"
        run: bash ./.github/workflows/update_pub.sh
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating publications"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
