name: Github Actions
on: [push]
jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: echo "performing readme merge from publications document"
      - name: "performing command"
        run: bash ./update_pub.sh
