name: Github Actions
on: [push]
jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - run: echo "performing readme merge from publications document"
      - uses: actions/checkout@v1
      - name: "performing command"
        run: bash ./.github/workflows/update_pub.sh
      - name: "Commit Files"
        run: |
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git commit -m "updated publications" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
